/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.dao_oçamento;
import javax.swing.JOptionPane;
import model.modelOçamento;

/**
 *
 * @author Matheus
 */
public class Oçamento extends javax.swing.JFrame {

    /**
     * Creates new form Oçamento
     */
    public Oçamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXT_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXT_servicos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXT_produto = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_telefone = new javax.swing.JFormattedTextField();
        TXT_cpf = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        BT_Sequir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_home = new javax.swing.JMenu();
        MENU_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 128, 128));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("OÇAMENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 80));

        jPanel2.setBackground(new java.awt.Color(169, 169, 169));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 16, 56, 19));
        jPanel2.add(TXT_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 41, 200, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel3.setText("E-mail:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 79, -1, -1));
        jPanel2.add(TXT_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 200, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 140, 43, -1));

        TXT_servicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Concerto", "Manutenção ", "Instalação" }));
        jPanel2.add(TXT_servicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel5.setText("Serviços:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel6.setText("Produto:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        TXT_produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Notbook", "Desktop", "Mobile", "Consoler", "Outros" }));
        jPanel2.add(TXT_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, -1));

        jTextField4.setToolTipText("O");
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 150, -1));
        jTextField4.getAccessibleContext().setAccessibleDescription("Outros"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel7.setText("Telefone:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        try {
            TXT_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXT_telefone.setName("D"); // NOI18N
        jPanel2.add(TXT_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 140, -1));

        try {
            TXT_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(TXT_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 200, -1));

        jButton1.setText("Cancelar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        BT_Sequir.setText("Seguir");
        BT_Sequir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SequirActionPerformed(evt);
            }
        });
        jPanel2.add(BT_Sequir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jButton3.setText("Sair");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 760, 360));

        MENU_home.setText("Home");
        MENU_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENU_homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(MENU_home);

        MENU_sair.setText("Sair");
        MENU_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENU_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MENU_sair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MENU_sairMouseClicked

    private void MENU_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_homeMouseClicked
        new TelaInicial().setVisible(true);
       dispose();
    }//GEN-LAST:event_MENU_homeMouseClicked

    private void BT_SequirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SequirActionPerformed
        modelOçamento c = new modelOçamento();
        c.setNome(TXT_nome.getText());
        c.setEmail(TXT_email.getText());
        c.setCpf(TXT_cpf.getText());
        c.setServicos(TXT_servicos.getItemAt(WIDTH));
        c.setProdutos(TXT_produto.getItemAt(WIDTH));
        c.setTelefone(TXT_telefone.getText());

        

        // fazendo a validação dos dados
        if ((TXT_nome.getText().isEmpty()) || (TXT_email.getText().isEmpty()) || (TXT_cpf.getText().isEmpty()) || (TXT_servicos.getItemAt(WIDTH).isEmpty())|| (TXT_produto.getItemAt(WIDTH).isEmpty()) || (TXT_telefone.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Informe valores para os campos");
        } else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            dao_oçamento dao = new dao_oçamento();
            dao.adiciona (c);
            JOptionPane.showMessageDialog(null, "orcamento " + TXT_nome.getText() + " inserido com sucesso! ");
        
    }//GEN-LAST:event_BT_SequirActionPerformed
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oçamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oçamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oçamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oçamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oçamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Sequir;
    private javax.swing.JMenu MENU_home;
    private javax.swing.JMenu MENU_sair;
    private javax.swing.JFormattedTextField TXT_cpf;
    private javax.swing.JTextField TXT_email;
    private javax.swing.JTextField TXT_nome;
    private javax.swing.JComboBox<String> TXT_produto;
    private javax.swing.JComboBox<String> TXT_servicos;
    private javax.swing.JFormattedTextField TXT_telefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
