/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TX_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TX_senha = new javax.swing.JTextField();
        BT_cadasT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BT_oçamento = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_home = new javax.swing.JMenu();
        MENU_Ocamento = new javax.swing.JMenu();
        MENU_Sair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 128, 128));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Hey Fun", 1, 36)); // NOI18N
        jLabel1.setText("IV ASSISTENCE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 0, 310, 80);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 80));

        jPanel2.setBackground(new java.awt.Color(169, 169, 169));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("E-mail");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 97, -1));
        jPanel2.add(TX_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 200, 30));

        jLabel3.setText("Senha");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));
        jPanel2.add(TX_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 200, 30));

        BT_cadasT.setText("Entrar");
        BT_cadasT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_cadasTActionPerformed(evt);
            }
        });
        jPanel2.add(BT_cadasT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LOGO.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 299, 273));

        BT_oçamento.setText("Oçamento");
        BT_oçamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_oçamentoActionPerformed(evt);
            }
        });
        jPanel2.add(BT_oçamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 770, 450));

        MENU_home.setText("Home");
        MENU_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENU_homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(MENU_home);

        MENU_Ocamento.setText("Oçamento");
        MENU_Ocamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENU_OcamentoMouseClicked(evt);
            }
        });
        jMenuBar1.add(MENU_Ocamento);

        MENU_Sair.setText("Sair");
        MENU_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENU_SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MENU_Sair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_SairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MENU_SairMouseClicked

    private void MENU_OcamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_OcamentoMouseClicked
        new Oçamento().setVisible(true);
       dispose();
    }//GEN-LAST:event_MENU_OcamentoMouseClicked

    private void MENU_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_homeMouseClicked
        new TelaInicial().setVisible(true);
       dispose();
    }//GEN-LAST:event_MENU_homeMouseClicked

    private void BT_cadasTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_cadasTActionPerformed
        if(TX_email.getText().equals("weareiv@gmail.com")&&TX_senha.getText().equals("mree2019")){
            Tecnico tecnico = new Tecnico();
                tecnico.setVisible(true);
                dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Negado");
        }
    }//GEN-LAST:event_BT_cadasTActionPerformed

    private void BT_oçamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_oçamentoActionPerformed
        new Oçamento().setVisible(true);
       dispose();    }//GEN-LAST:event_BT_oçamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_cadasT;
    private javax.swing.JButton BT_oçamento;
    private javax.swing.JMenu MENU_Ocamento;
    private javax.swing.JMenu MENU_Sair;
    private javax.swing.JMenu MENU_home;
    private javax.swing.JTextField TX_email;
    private javax.swing.JTextField TX_senha;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
